name: t20_app

description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7
  connectivity_plus: ^3.0.2
  fluttertoast: ^8.1.2
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  background_image: "assets/splash.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
     - assets/data/ttwenty.json
     - assets/flags/
     - assets/venues/
     - assets/images/
     - assets/splash.png